### ISSUE TITLE
No "unserialized" option available for persistence adapter

### ISSUE THREAD

**Issue by jordanmorris** [jd78/NodeEventStore#2]
Some persistence technologies have javascript client APIs which accept a javascript object, and do their own serialization.

Additionally, certain event stores (such as geteventstore) may not be expecting an object structured exactly like the event passed into the save method of the persistor. In such cases, it would be optimal to be able to map the fields and structure of the event onto a different object before persisting it.

I suggest we add an option called `payloadSerializationFormat` with multiple options:

- `unserialized /*The actual javascript object*/`
- `stringify /*The current default stringified object*/`
- `zip /*stringified and zipped*/`

These options could be defined as constants in the configuration module.

We could then deprecate the `zipPayload` option, and have it set the `zip` option for now, for backwards compatibility.

I welcome your feedback. Unless I hear from you, I'll proceed down this path to create a PR. Cheers.

**Comment by jd78** [comment]
Hi,

I see, it would be great, please go ahead with it.

Cheers,

Gennaro

**Comment by jordanmorris** [comment]
I believe normally these are left open until fixed. Cheers.
